# Generated by Django 6.0.1 on 2026-02-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='winners_public',
            field=models.BooleanField(default=False),
        ),
    ]
