# Generated by Django 6.0.1 on 2026-02-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_winners_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sponsor_logo',
            field=models.ImageField(blank=True, null=True, upload_to='sponsors/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='event',
            name='sponsor_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='sponsor_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='event',
            name='sponsor_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
