# Generated by Django 6.0.1 on 2026-02-07 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_sponsor_logo_event_sponsor_message_and_more'),
        ('teams', '0002_teampinnedvehicle_teamtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='teams.team'),
        ),
    ]
