# Generated by Django 6.0.1 on 2026-02-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_organizer_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/'),
        ),
    ]
