# Generated by Django 6.0.1 on 2026-02-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
