# Generated by Django 6.0.1 on 2026-02-01 16:13

import apps.common.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicleimage_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleimage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/thumbs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(upload_to=apps.common.upload.upload_vehicle_image),
        ),
    ]
