# Generated by Django 6.0.1 on 2026-02-02 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_remove_vehicleimage_created_at_vehicleimage_thumb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservehicle',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vehicles.vehicleimage'),
        ),
    ]
