# Generated by Django 6.0.1 on 2026-02-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_uservehicle_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservehicle',
            name='seat',
            field=models.CharField(blank=True, default='', help_text='例: タックロール / 純正 / 社外', max_length=120),
        ),
        migrations.AddField(
            model_name='uservehicle',
            name='tire_maker',
            field=models.CharField(blank=True, choices=[('bridgestone', 'Bridgestone'), ('michelin', 'Michelin'), ('dunlop', 'Dunlop'), ('pirelli', 'Pirelli'), ('yokohama', 'Yokohama'), ('toyo', 'Toyo Tires'), ('continental', 'Continental'), ('other', 'Other')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='uservehicle',
            name='tire_size',
            field=models.CharField(blank=True, default='', help_text='例: 90/90-17', max_length=32),
        ),
    ]
