# Generated by Django 6.0.1 on 2026-02-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_uservehicle_seat_uservehicle_tire_maker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservehicle',
            name='specs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
