# Generated by Django 6.0.1 on 2026-02-07 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_maker_partcategory_part_vehiclepart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclepart',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='vehiclepart',
            name='part_free_text',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='vehiclepart',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_parts', to='vehicles.part'),
        ),
    ]
