# Generated by Django 6.0.1 on 2026-02-07 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_alter_vehiclepart_options_vehiclepart_part_free_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservehicle',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='uservehicle',
            name='tire_maker',
        ),
        migrations.RemoveField(
            model_name='uservehicle',
            name='tire_size',
        ),
    ]
