# Generated by Django 6.0.1 on 2026-02-07 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('vehicles', '0009_remove_uservehicle_seat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPinnedVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_vehicles', to='teams.team')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_in_teams', to='vehicles.uservehicle')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('team', 'vehicle'), name='uniq_team_vehicle_pin')],
            },
        ),
        migrations.CreateModel(
            name='TeamTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='teams.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('team', 'name'), name='uniq_team_tag')],
            },
        ),
    ]
