# Generated by Django 6.0.1 on 2026-02-01 16:13

import apps.common.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to=apps.common.upload.upload_post_image),
        ),
    ]
